import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./styles.css";

const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
const defaultChannels=["Cash","bKash","Nagad","Rocket","Upay","Bank"];
const roleOptions=["pending","agent","member","manager","admin","super_admin"];
const money=n=>new Intl.NumberFormat("en-BD",{maximumFractionDigits:2}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const tabIcons={dashboard:"📊",transactions:"💸",ledger:"📒",closing:"🧾",people:"👥",reports:"📈",settings:"⚙️",audit:"🕵️",users:"🔑"};

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState("dashboard"),[msg,setMsg]=useState("");
 const [profile,setProfile]=useState(null),[members,setMembers]=useState([]),[agents,setAgents]=useState([]),[tx,setTx]=useState([]),[closings,setClosings]=useState([]),[openingsDb,setOpeningsDb]=useState([]);
 const [channelsDb,setChannelsDb]=useState([]),[users,setUsers]=useState([]),[auditLog,setAuditLog]=useState([]),[newChannel,setNewChannel]=useState("");
 const [reminder,setReminderState]=useState(()=>(typeof localStorage!=="undefined"&&localStorage.getItem("isf_reminder"))||"");
 const [form,setForm]=useState({type:"collection",person_type:"agent",person_id:"",channel:"bKash",amount:"",note:"",transaction_date:today()});
 const [person,setPerson]=useState({name:"",phone:"",type:"agent"}),[closeDate,setCloseDate]=useState(today());
 const [opening,setOpening]=useState({date:today(),channel:"Cash",amount:"",note:""}),[editing,setEditing]=useState(null),[filter,setFilter]=useState({dateFrom:"",dateTo:"",person:"",channel:"",type:""});
 const [theme,setTheme]=useState(()=>{if(typeof localStorage==="undefined")return "light";const saved=localStorage.getItem("isf_theme");if(saved)return saved;return (typeof window!=="undefined"&&window.matchMedia?.("(prefers-color-scheme: dark)").matches)?"dark":"light"});

 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 useEffect(()=>{document.documentElement.setAttribute("data-theme",theme);localStorage.setItem("isf_theme",theme);document.querySelector('meta[name="theme-color"]')?.setAttribute("content",theme==="dark"?"#05080f":"#0f172a")},[theme]);
 function toggleTheme(){setTheme(t=>t==="dark"?"light":"dark")}

 // Daily-closing browser reminder. Client-side only: fires while this tab is
 // open on this device. Real SMS/email needs a backend + provider (see README).
 useEffect(()=>{
  if(!reminder||typeof Notification==="undefined")return;
  const iv=setInterval(()=>{
   const now=new Date();const hh=String(now.getHours()).padStart(2,"0"),mm=String(now.getMinutes()).padStart(2,"0");
   if(`${hh}:${mm}`===reminder&&now.getSeconds()<20&&Notification.permission==="granted"){new Notification("ISF Business Ledger",{body:"Reminder: complete today's daily closing."})}
  },15000);
  return()=>clearInterval(iv);
 },[reminder]);

 async function load(){
  const {data:p,error:pErr}=await supabase.from("profiles").select("*").eq("id",session.user.id).maybeSingle();
  if(!pErr)setProfile(p);
  if(!p||p.role==="pending")return; // RLS blocks everything else for pending accounts anyway
  const [m,a,t,c,o,ch,us,al]=await Promise.all([
   supabase.from("members").select("*").order("name"),
   supabase.from("agents").select("*").order("name"),
   supabase.from("transactions").select("*").order("transaction_date",{ascending:false}).order("created_at",{ascending:false}),
   supabase.from("daily_closings").select("*").order("closing_date",{ascending:false}),
   supabase.from("opening_balances").select("*").order("balance_date",{ascending:false}),
   supabase.from("channels").select("*").order("sort_order",{ascending:true}).order("name"),
   supabase.from("profiles").select("*").order("created_at",{ascending:false}),
   supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(300)
  ]);
  if(!m.error)setMembers(m.data||[]);if(!a.error)setAgents(a.data||[]);if(!t.error)setTx(t.data||[]);if(!c.error)setClosings(c.data||[]);if(!o.error)setOpeningsDb(o.data||[]);
  if(!ch.error)setChannelsDb(ch.data||[]);if(!us.error)setUsers(us.data||[]);if(!al.error)setAuditLog(al.data||[]);
 }

 const people=useMemo(()=>[...members.map(x=>({...x,person_type:"member"})),...agents.map(x=>({...x,person_type:"agent"}))],[members,agents]);
 const name=id=>people.find(p=>p.id===id)?.name||"Unknown";
 const allowed=(...roles)=>roles.includes(profile?.role)||profile?.role==="super_admin";
 const canManage=allowed("super_admin","admin","manager"),canAdmin=allowed("super_admin","admin");
 const channelNames=useMemo(()=>{const act=channelsDb.filter(c=>c.active).map(c=>c.name);return act.length?act:defaultChannels},[channelsDb]);
 const allChannelNames=useMemo(()=>[...new Set([...channelsDb.map(c=>c.name),...tx.map(t=>t.channel),...defaultChannels])],[channelsDb,tx]);
 const totals=useMemo(()=>sumTx(tx),[tx]);
 const dayTx=useMemo(()=>tx.filter(t=>t.transaction_date===closeDate),[tx,closeDate]);
 const dayStats=useMemo(()=>sumTx(dayTx),[dayTx]);
 const dayOpenings=useMemo(()=>openingsDb.filter(x=>x.balance_date===closeDate),[openingsDb,closeDate]);
 const channelClosing=useMemo(()=>channelNames.map(ch=>{const op=dayOpenings.filter(x=>x.channel===ch).reduce((s,x)=>s+ +x.amount,0);const d=dayTx.filter(x=>x.channel===ch).reduce((s,x)=>s+(x.type==="collection"?+x.amount:x.type==="fund_given"||x.type==="expense"?-+x.amount:0),0);return {channel:ch,opening:op,movement:d,closing:op+d}}),[channelNames,dayOpenings,dayTx]);

 function sumTx(rows){return rows.reduce((a,t)=>{const v=+t.amount||0;if(t.type==="fund_given")a.fund+=v;if(t.type==="collection")a.collection+=v;if(t.type==="expense")a.expense+=v;return a},{fund:0,collection:0,expense:0})}
 async function audit(action,table,rowId,details=""){await supabase.from("audit_logs").insert({user_id:session.user.id,user_email:session.user.email,action,table_name:table,row_id:rowId,details})}
 async function login(){const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin}});if(error)setMsg(error.message)}
 async function logout(){await supabase.auth.signOut()}

 async function addPerson(e){e.preventDefault();if(!allowed("admin","manager"))return setMsg("Permission denied.");const table=person.type==="member"?"members":"agents";const {data,error}=await supabase.from(table).insert({name:person.name.trim(),phone:person.phone.trim(),active:true}).select().single();if(!error)await audit("CREATE",table,data.id,person.name);setMsg(error?.message||"Added.");if(!error){setPerson({...person,name:"",phone:""});load()}}
 async function togglePerson(p){if(!allowed("admin","manager"))return setMsg("Permission denied.");const table=p.person_type==="member"?"members":"agents";const {error}=await supabase.from(table).update({active:!p.active}).eq("id",p.id);if(!error)await audit("UPDATE",table,p.id,`active -> ${!p.active}`);setMsg(error?.message||"Updated.");if(!error)load()}

 async function saveTx(e){e.preventDefault();if(!allowed("admin","manager","member","agent"))return setMsg("Permission denied.");if(!form.person_id||!+form.amount)return setMsg("Select person and amount.");let error,data;
  if(editing){({error}=await supabase.from("transactions").update({...form,amount:+form.amount}).eq("id",editing));if(!error)await audit("UPDATE","transactions",editing,JSON.stringify(form));setMsg(error?.message||"Transaction updated.");setEditing(null)}
  else {({data,error}=await supabase.from("transactions").insert({...form,amount:+form.amount,created_by:session.user.id}).select().single());if(!error)await audit("CREATE","transactions",data.id,JSON.stringify(form));setMsg(error?.message||"Transaction saved.")}
  if(!error){setForm({...form,person_id:"",amount:"",note:""});load()}
 }
 function editTx(t){setEditing(t.id);setForm({type:t.type,person_type:t.person_type,person_id:t.person_id,channel:t.channel,amount:t.amount,note:t.note||"",transaction_date:t.transaction_date});setTab("transactions")}
 async function deleteTx(id){if(!allowed("admin","manager"))return setMsg("Only Admin/Manager can delete.");if(!confirm("Delete this transaction?"))return;const {error}=await supabase.from("transactions").delete().eq("id",id);if(!error)await audit("DELETE","transactions",id,"Transaction deleted");setMsg(error?.message||"Transaction deleted.");if(!error)load()}
 async function addOpening(e){e.preventDefault();if(!allowed("admin","manager"))return setMsg("Permission denied.");const {data,error}=await supabase.from("opening_balances").insert({...opening,amount:+opening.amount,created_by:session.user.id}).select().single();if(!error)await audit("CREATE","opening_balances",data.id,JSON.stringify(opening));setMsg(error?.message||"Opening balance saved.");if(!error){setOpening({...opening,amount:"",note:""});load()}}
 async function dailyClose(){if(!allowed("admin","manager","super_admin"))return setMsg("Only authorized users can close a day.");const net=dayStats.collection-dayStats.fund-dayStats.expense;const {data,error}=await supabase.from("daily_closings").upsert({closing_date:closeDate,total_fund:dayStats.fund,total_collection:dayStats.collection,total_expense:dayStats.expense,net_result:net,closed_by:session.user.id},{onConflict:"closing_date"}).select().single();if(!error)await audit("CLOSE","daily_closings",data.id,closeDate);setMsg(error?.message||"Daily closing saved.");if(!error)load()}
 function personLedger(id,date=""){const rows=tx.filter(t=>t.person_id===id&&(!date||t.transaction_date===date));return sumTx(rows)}

 async function updateUserRole(id,role){if(!allowed("super_admin","admin"))return setMsg("Permission denied.");const {error}=await supabase.from("profiles").update({role}).eq("id",id);if(!error)await audit("UPDATE","profiles",id,`role -> ${role}`);setMsg(error?.message||"User updated.");if(!error)load()}
 async function addChannel(e){e.preventDefault();if(!canManage)return setMsg("Permission denied.");const nm=newChannel.trim();if(!nm)return setMsg("Enter a channel name.");const {data,error}=await supabase.from("channels").insert({name:nm}).select().single();if(!error)await audit("CREATE","channels",data.id,nm);setMsg(error?.message||"Channel added.");if(!error){setNewChannel("");load()}}
 async function toggleChannel(c){if(!canManage)return setMsg("Permission denied.");const {error}=await supabase.from("channels").update({active:!c.active}).eq("id",c.id);if(!error)await audit("UPDATE","channels",c.id,`active -> ${!c.active}`);setMsg(error?.message||"Channel updated.");if(!error)load()}
 function enableReminder(time){if(!time)return;if(typeof Notification!=="undefined"&&Notification.permission!=="granted"){Notification.requestPermission().then(perm=>{if(perm==="granted"){localStorage.setItem("isf_reminder",time);setReminderState(time)}else setMsg("Browser notification permission was denied.")});return}localStorage.setItem("isf_reminder",time);setReminderState(time)}
 function disableReminder(){localStorage.removeItem("isf_reminder");setReminderState("")}

 function reportText(){return `ISF Daily Report ${closeDate}\nFund Given: ৳${money(dayStats.fund)}\nCollection: ৳${money(dayStats.collection)}\nExpense: ৳${money(dayStats.expense)}\nNet Result: ৳${money(dayStats.collection-dayStats.fund-dayStats.expense)}\n\nChannel Closing:\n${channelClosing.map(x=>`${x.channel}: ৳${money(x.closing)}`).join("\n")}`}
 function shareText(){const text=reportText();navigator.clipboard?.writeText(text);if(navigator.share)navigator.share({title:"ISF Daily Report",text}).catch(()=>{});else setMsg("Report copied.")}
 function shareWhatsApp(){window.open(`https://wa.me/?text=${encodeURIComponent(reportText())}`,"_blank")}
 function shareTelegram(){window.open(`https://t.me/share/url?url=&text=${encodeURIComponent(reportText())}`,"_blank")}
 function makePDF(){const d=new jsPDF();d.text("ISF Business Ledger V4",14,15);d.text(`Daily Report: ${closeDate}`,14,23);d.autoTable({startY:30,head:[["Date","Type","Person","Channel","Amount"]],body:dayTx.map(t=>[t.transaction_date,t.type,name(t.person_id),t.channel,money(t.amount)])});const y=(d.lastAutoTable?.finalY||50)+12;d.text(`Fund: ${money(dayStats.fund)} | Collection: ${money(dayStats.collection)} | Expense: ${money(dayStats.expense)}`,14,y);d.text(`Net Result: ${money(dayStats.collection-dayStats.fund-dayStats.expense)}`,14,y+8);return d}
 function exportPDF(){makePDF().save(`ISF-Daily-${closeDate}.pdf`)}
 async function sharePDF(){const d=makePDF();const blob=d.output("blob");const file=new File([blob],`ISF-Daily-${closeDate}.pdf`,{type:"application/pdf"});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:"ISF Daily Report",text:reportText(),files:[file]});return}catch(e){}}exportPDF();setMsg("PDF downloaded. WhatsApp/Telegram direct links cannot attach local files; use the phone Share option when supported.")}
 function exportExcel(){const rows=tx.map(t=>({Date:t.transaction_date,Type:t.type,Person:name(t.person_id),Channel:t.channel,Amount:+t.amount,Note:t.note||""}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Transactions");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(people.map(p=>({Type:p.person_type,Name:p.name,Phone:p.phone||"",Fund:personLedger(p.id).fund,Collection:personLedger(p.id).collection,Expense:personLedger(p.id).expense,Net:personLedger(p.id).collection-personLedger(p.id).fund-personLedger(p.id).expense}))),"People Ledger");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(channelClosing),"Channel Closing");XLSX.writeFile(wb,`ISF-V4-${today()}.xlsx`)}
 const filtered=useMemo(()=>tx.filter(t=>(!filter.dateFrom||t.transaction_date>=filter.dateFrom)&&(!filter.dateTo||t.transaction_date<=filter.dateTo)&&(!filter.person||t.person_id===filter.person)&&(!filter.channel||t.channel===filter.channel)&&(!filter.type||t.type===filter.type)),[tx,filter]);

 if(!supabase)return <Setup/>;
 if(loading)return <div className="center">Loading...</div>;
 if(!session)return <Login login={login} message={msg}/>;
 if(!profile||profile.role==="pending")return <PendingScreen email={session.user.email} status={profile?"pending":"provisioning"} refresh={load} logout={logout}/>;

 const tabs=["dashboard","transactions","ledger","closing","people","reports","settings",...(canManage?["audit"]:[]),...(canAdmin?["users"]:[])];
 return <div className="app"><header className="topbar"><b>ISF Business Ledger <span>V4</span></b><div className="user"><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle dark mode" title="Toggle dark mode">{theme==="dark"?"☀️":"🌙"}</button><span>{session.user.email}</span><button onClick={logout}>Logout</button></div></header><div className="layout"><aside>{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}><span className="icon">{tabIcons[x]||"•"}</span><span>{x[0].toUpperCase()+x.slice(1)}</span></button>)}</aside><main>{msg&&<div className="notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
 {tab==="dashboard"&&<Dashboard totals={totals} dayStats={dayStats} date={closeDate} people={people} tx={tx} channelClosing={channelClosing}/>}
 {tab==="transactions"&&<Transactions form={form} setForm={setForm} submit={saveTx} members={members} agents={agents} editing={editing} cancel={()=>{setEditing(null);setForm({...form,person_id:"",amount:"",note:""})}} channelNames={channelNames}/>}
 {tab==="ledger"&&<Ledger agents={agents} members={members} ledger={personLedger} date={closeDate} setDate={setCloseDate}/>}
 {tab==="closing"&&<Closing date={closeDate} setDate={setCloseDate} stats={dayStats} close={dailyClose} openings={opening} setOpening={setOpening} addOpening={addOpening} channelClosing={channelClosing} channelNames={channelNames} share={shareText} whatsapp={shareWhatsApp} telegram={shareTelegram} pdf={sharePDF}/>}
 {tab==="people"&&<People person={person} setPerson={setPerson} add={addPerson} members={members} agents={agents} toggle={togglePerson} canManage={canManage}/>}
 {tab==="reports"&&<Reports tx={filtered} allTx={tx} name={name} pdf={exportPDF} excel={exportExcel} filter={filter} setFilter={setFilter} edit={editTx} del={deleteTx} people={people} allChannelNames={allChannelNames}/>}
 {tab==="settings"&&<Settings profile={profile} channelsDb={channelsDb} canManage={canManage} newChannel={newChannel} setNewChannel={setNewChannel} addChannel={addChannel} toggleChannel={toggleChannel} reminder={reminder} enableReminder={enableReminder} disableReminder={disableReminder}/>}
 {tab==="audit"&&canManage&&<AuditLog auditLog={auditLog}/>}
 {tab==="users"&&canAdmin&&<UsersManagement users={users} updateUserRole={updateUserRole} currentUserId={session.user.id}/>}
 </main></div></div>
}

const Stat=({title,value})=><div className="card stat"><span>{title}</span><strong>৳ {money(value)}</strong></div>;
function Login({login,message}){return <div className="login"><div className="card login-card"><h1>ISF Business Ledger V4</h1><p>Distributor • Agent • Daily Settlement</p><button className="primary wide" onClick={login}>Continue with Google</button>{message&&<p className="error">{message}</p>}<small>Cloud saved • Mobile friendly • Secure roles • New accounts require admin approval</small></div></div>}
function PendingScreen({email,status,refresh,logout}){return <div className="login"><div className="card login-card"><h1>ISF Business Ledger V4</h1>{status==="pending"?<><p><b>Account pending approval</b></p><p className="muted">Signed in as {email}. A Super Admin or Admin needs to approve your account and assign a role before you can see or enter any data.</p></>:<><p><b>Setting up your account…</b></p><p className="muted">Signed in as {email}. This usually takes just a few seconds.</p></>}<div className="center-actions"><button className="primary" onClick={refresh}>Refresh</button><button onClick={logout}>Logout</button></div></div></div>}
function Setup(){return <div className="center"><div className="card"><h2>Supabase setup required</h2><p>Copy .env.example to .env, add Supabase credentials, and run supabase/schema.sql (new project) or supabase/migration_v3_to_v4.sql (existing project).</p></div></div>}

function Dashboard({totals,dayStats,date,people,tx,channelClosing}){return <section><h1>Dashboard</h1><p className="muted">Business overview — {date}</p><p className="muted small-note">Net Result = Collection − Fund Given − Expense · Channel Closing = Opening + Collection − Fund Given − Expense</p><div className="stats"><Stat title="Total Fund Given" value={totals.fund}/><Stat title="Total Collection" value={totals.collection}/><Stat title="Total Expense" value={totals.expense}/><Stat title="Day Net" value={dayStats.collection-dayStats.fund-dayStats.expense}/></div><div className="grid2"><div className="card"><h3>Today's Settlement</h3>{people.slice(0,8).map(p=>{const l=tx.filter(t=>t.person_id===p.id&&t.transaction_date===date);const s=l.reduce((a,t)=>a+(t.type==="fund_given"?+t.amount:t.type==="collection"?-+t.amount:0),0);return <div className="ledgerrow" key={p.id}><b>{p.name}</b><span>{p.person_type}</span><strong>Balance ৳{money(s)}</strong></div>})}</div><div className="card"><h3>Channel Snapshot ({date})</h3>{channelClosing.map(x=><div className="ledgerrow" key={x.channel}><b>{x.channel}</b><span>Opening ৳{money(x.opening)}</span><strong>Closing ৳{money(x.closing)}</strong></div>)}</div></div></section>}

function Transactions({form,setForm,submit,members,agents,editing,cancel,channelNames}){let ps=(form.person_type==="member"?members:agents).filter(p=>p.active);return <section><h1>{editing?"Edit Transaction":"Transactions"}</h1><form className="card form" onSubmit={submit}><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="collection">Collection</option><option value="fund_given">Fund Given</option><option value="expense">Expense</option></select></label><label>Person Type<select value={form.person_type} onChange={e=>setForm({...form,person_type:e.target.value,person_id:""})}><option value="agent">Agent</option><option value="member">Member</option></select></label><label>Person<select value={form.person_id} onChange={e=>setForm({...form,person_id:e.target.value})}><option value="">Select...</option>{ps.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Channel<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}>{channelNames.map(x=><option key={x}>{x}</option>)}</select></label><label>Amount<input required type="number" min="0.01" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><label className="full">Note<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="actions"><button className="primary">{editing?"Update Transaction":"Save Transaction"}</button>{editing&&<button type="button" onClick={cancel}>Cancel</button>}</div></form></section>}

function Ledger({agents,members,ledger,date,setDate}){return <section><div className="section-head"><div><h1>Individual Ledger</h1><p className="muted">Select a date for daily settlement.</p></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="grid2"><LedgerList title="Agents" items={agents} ledger={ledger} date={date}/><LedgerList title="Members / Distributors" items={members} ledger={ledger} date={date}/></div></section>}
function LedgerList({title,items,ledger,date}){return <div className="card"><h3>{title}</h3>{items.map(p=>{const l=ledger(p.id,date);return <div className="ledgerrow" key={p.id}><b>{p.name}</b><span>Fund ৳{money(l.fund)} · Collection ৳{money(l.collection)} · Expense ৳{money(l.expense)}</span><strong>Net ৳{money(l.collection-l.fund-l.expense)}</strong></div>})}</div>}

function Closing({date,setDate,stats,close,openings,setOpening,addOpening,channelClosing,channelNames,share,whatsapp,telegram,pdf}){return <section><div className="section-head"><div><h1>Daily Closing</h1><p className="muted">Opening → transactions → closing</p></div><input type="date" value={date} onChange={e=>{setDate(e.target.value);setOpening({...openings,date:e.target.value})}}/></div><div className="stats"><Stat title="Fund Given" value={stats.fund}/><Stat title="Collection" value={stats.collection}/><Stat title="Expense" value={stats.expense}/><Stat title="Net Result" value={stats.collection-stats.fund-stats.expense}/></div><div className="card"><h3>Opening Balance</h3><form className="form" onSubmit={addOpening}><label>Channel<select value={openings.channel} onChange={e=>setOpening({...openings,channel:e.target.value})}>{channelNames.map(x=><option key={x}>{x}</option>)}</select></label><label>Amount<input required type="number" min="0" step=".01" value={openings.amount} onChange={e=>setOpening({...openings,amount:e.target.value,date})}/></label><label>Note<input value={openings.note} onChange={e=>setOpening({...openings,note:e.target.value,date})}/></label><button className="primary">Save Opening</button></form></div><div className="card"><h3>Channel Closing</h3><div className="table-wrap"><table><thead><tr><th>Channel</th><th>Opening</th><th>Movement</th><th>Closing</th></tr></thead><tbody>{channelClosing.map(x=><tr key={x.channel}><td>{x.channel}</td><td>৳{money(x.opening)}</td><td>৳{money(x.movement)}</td><td><b>৳{money(x.closing)}</b></td></tr>)}</tbody></table></div></div><div className="actions"><button className="primary" onClick={close}>Close This Day</button><button onClick={pdf}>📄 Share PDF</button><button onClick={share}>📤 Share</button><button className="wa" onClick={whatsapp}>WhatsApp</button><button className="tg" onClick={telegram}>Telegram</button></div></section>}

function People({person,setPerson,add,members,agents,toggle,canManage}){return <section><h1>People Management</h1><form className="card form" onSubmit={add}><label>Type<select value={person.type} onChange={e=>setPerson({...person,type:e.target.value})}><option value="agent">Agent</option><option value="member">Member/Distributor</option></select></label><label>Name<input required value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/></label><label>Phone<input value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/></label><button className="primary">Add</button></form><div className="grid2"><List title="Members" items={members.map(m=>({...m,person_type:"member"}))} toggle={toggle} canManage={canManage}/><List title="Agents" items={agents.map(a=>({...a,person_type:"agent"}))} toggle={toggle} canManage={canManage}/></div></section>}
const List=({title,items,toggle,canManage})=><div className="card"><h3>{title}</h3>{items.map(x=><div className="listrow" key={x.id}><b>{x.name}</b><span>{x.phone||""} <span className={"badge "+(x.active?"active":"inactive")}>{x.active?"Active":"Inactive"}</span></span>{canManage&&<button onClick={()=>toggle(x)}>{x.active?"Deactivate":"Activate"}</button>}</div>)}</div>;

function Reports({tx,allTx,name,pdf,excel,filter,setFilter,edit,del,people,allChannelNames}){return <section><div className="section-head"><div><h1>Reports</h1><p className="muted">Search, edit, delete and export.</p></div><div className="actions"><button onClick={pdf}>PDF</button><button onClick={excel}>Excel</button></div></div><div className="card form"><label>From<input type="date" value={filter.dateFrom} onChange={e=>setFilter({...filter,dateFrom:e.target.value})}/></label><label>To<input type="date" value={filter.dateTo} onChange={e=>setFilter({...filter,dateTo:e.target.value})}/></label><label>Person<select value={filter.person} onChange={e=>setFilter({...filter,person:e.target.value})}><option value="">All</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Channel<select value={filter.channel} onChange={e=>setFilter({...filter,channel:e.target.value})}><option value="">All</option>{allChannelNames.map(c=><option key={c}>{c}</option>)}</select></label><label>Type<select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})}><option value="">All</option><option value="collection">Collection</option><option value="fund_given">Fund Given</option><option value="expense">Expense</option></select></label></div><div className="card"><div className="muted">Showing {tx.length} of {allTx.length} transactions</div><Table tx={tx} name={name} edit={edit} del={del}/></div></section>}
function Table({tx,name,edit,del}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Person</th><th>Channel</th><th>Amount</th><th>Note</th><th>Action</th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td>{t.transaction_date}</td><td>{t.type}</td><td>{name(t.person_id)}</td><td>{t.channel}</td><td>৳ {money(t.amount)}</td><td>{t.note||""}</td><td><button onClick={()=>edit(t)}>Edit</button><button className="danger" onClick={()=>del(t.id)}>Delete</button></td></tr>)}</tbody></table></div>}

function Settings({profile,channelsDb,canManage,newChannel,setNewChannel,addChannel,toggleChannel,reminder,enableReminder,disableReminder}){return <section><h1>Settings</h1><div className="card"><h3>Role & Security</h3><p>Current role: <b>{profile?.role}</b></p><p className="muted">Roles: Super Admin, Admin, Manager, Member, Agent. New Google sign-ins start as <b>Pending</b> and need approval from a Super Admin/Admin in the Users tab before they can see any data.</p><p className="muted">Every create/update/delete/closing/role-change action is written to the Audit Log.</p></div><div className="card"><h3>Daily Closing Reminder</h3><p className="muted">Browser notification only — fires while this app is open in a tab on this device. For real SMS/email alerts you'd need a backend function plus a provider (e.g. a Supabase Edge Function + email/SMS API) — not included yet.</p><div className="form"><label>Reminder time<input type="time" defaultValue={reminder} onBlur={e=>e.target.value&&enableReminder(e.target.value)}/></label></div>{reminder&&<div className="actions"><button onClick={disableReminder}>Turn off ({reminder})</button></div>}</div>{canManage&&<div className="card"><h3>Payment Channels</h3><form className="form" onSubmit={addChannel}><label className="full">New channel name<input value={newChannel} onChange={e=>setNewChannel(e.target.value)} placeholder="e.g. Tap, DBBL Nexus"/></label><button className="primary">Add Channel</button></form>{channelsDb.map(c=><div className="listrow" key={c.id}><b>{c.name}</b><span className={"badge "+(c.active?"active":"inactive")}>{c.active?"Active":"Inactive"}</span><button onClick={()=>toggleChannel(c)}>{c.active?"Deactivate":"Activate"}</button></div>)}{!channelsDb.length&&<p className="muted">Using default channels (Cash, bKash, Nagad, Rocket, Upay, Bank). Run the migration script to manage channels here.</p>}</div>}</section>}

function UsersManagement({users,updateUserRole,currentUserId}){return <section><h1>User Management</h1><p className="muted">Approve pending sign-ins and manage roles. New Google logins default to Pending until approved here.</p><div className="card"><div className="table-wrap"><table><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Joined</th><th>Change Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.email}</td><td>{u.full_name||""}</td><td><span className={"badge "+(u.role==="pending"?"pending":"active")}>{u.role}</span></td><td>{(u.created_at||"").slice(0,10)}</td><td><select defaultValue={u.role} onChange={e=>updateUserRole(u.id,e.target.value)} disabled={u.id===currentUserId}>{roleOptions.map(r=><option key={r} value={r}>{r}</option>)}</select></td></tr>)}</tbody></table></div>{!users.length&&<p className="muted">No users found, or you don't have permission to view this list.</p>}</div></section>}

function AuditLog({auditLog}){return <section><h1>Audit Log</h1><p className="muted">Most recent 300 actions. Visible to Super Admin, Admin and Manager.</p><div className="card"><div className="table-wrap"><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Table</th><th>Details</th></tr></thead><tbody>{auditLog.map(a=><tr key={a.id}><td>{(a.created_at||"").replace("T"," ").slice(0,19)}</td><td>{a.user_email||a.user_id}</td><td>{a.action}</td><td>{a.table_name}</td><td>{a.details}</td></tr>)}</tbody></table></div>{!auditLog.length&&<p className="muted">No audit entries yet.</p>}</div></section>}

createRoot(document.getElementById("root")).render(<App/>);
