import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./styles.css";

const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
const channels=["Cash","bKash","Nagad","Rocket","Upay","Bank"];
const money=n=>new Intl.NumberFormat("en-BD",{maximumFractionDigits:2}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState("dashboard"),[msg,setMsg]=useState("");
 const [profile,setProfile]=useState(null),[members,setMembers]=useState([]),[agents,setAgents]=useState([]),[tx,setTx]=useState([]),[closings,setClosings]=useState([]),[openingsDb,setOpeningsDb]=useState([]);
 const [form,setForm]=useState({type:"collection",person_type:"agent",person_id:"",channel:"bKash",amount:"",note:"",transaction_date:today()});
 const [person,setPerson]=useState({name:"",phone:"",type:"agent"}),[closeDate,setCloseDate]=useState(today());
 const [opening,setOpening]=useState({date:today(),channel:"Cash",amount:"",note:""}),[editing,setEditing]=useState(null),[filter,setFilter]=useState({date:"",person:"",channel:"",type:""});
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const [p,m,a,t,c,o]=await Promise.all([
  supabase.from("profiles").select("*").eq("id",session.user.id).maybeSingle(),supabase.from("members").select("*").order("name"),supabase.from("agents").select("*").order("name"),
  supabase.from("transactions").select("*").order("transaction_date",{ascending:false}).order("created_at",{ascending:false}),supabase.from("daily_closings").select("*").order("closing_date",{ascending:false}),supabase.from("opening_balances").select("*").order("balance_date",{ascending:false})]);
  if(!p.error)setProfile(p.data);if(!m.error)setMembers(m.data||[]);if(!a.error)setAgents(a.data||[]);if(!t.error)setTx(t.data||[]);if(!c.error)setClosings(c.data||[]);if(!o.error)setOpeningsDb(o.data||[]);
 }
 const people=useMemo(()=>[...members.map(x=>({...x,person_type:"member"})),...agents.map(x=>({...x,person_type:"agent"}))],[members,agents]);
 const name=id=>people.find(p=>p.id===id)?.name||"Unknown";
 const allowed=(...roles)=>roles.includes(profile?.role)||profile?.role==="super_admin";
 const totals=useMemo(()=>sumTx(tx),[tx]);
 const dayTx=useMemo(()=>tx.filter(t=>t.transaction_date===closeDate),[tx,closeDate]);
 const dayStats=useMemo(()=>sumTx(dayTx),[dayTx]);
 const dayOpenings=useMemo(()=>openingsDb.filter(x=>x.balance_date===closeDate),[openingsDb,closeDate]);
 const channelClosing=useMemo(()=>channels.map(ch=>{const op=dayOpenings.filter(x=>x.channel===ch).reduce((s,x)=>s+ +x.amount,0);const d=dayTx.filter(x=>x.channel===ch).reduce((s,x)=>s+(x.type==="collection"?+x.amount:x.type==="fund_given"||x.type==="expense"?-+x.amount:0),0);return {channel:ch,opening:op,movement:d,closing:op+d}}),[dayOpenings,dayTx]);
 function sumTx(rows){return rows.reduce((a,t)=>{const v=+t.amount||0;if(t.type==="fund_given")a.fund+=v;if(t.type==="collection")a.collection+=v;if(t.type==="expense")a.expense+=v;return a},{fund:0,collection:0,expense:0})}
 async function audit(action,table,rowId,details=""){await supabase.from("audit_logs").insert({user_id:session.user.id,action,table_name:table,row_id:rowId,details})}
 async function login(){const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin}});if(error)setMsg(error.message)}
 async function logout(){await supabase.auth.signOut()}
 async function addPerson(e){e.preventDefault();if(!allowed("admin","manager"))return setMsg("Permission denied.");const table=person.type==="member"?"members":"agents";const {data,error}=await supabase.from(table).insert({name:person.name.trim(),phone:person.phone.trim(),active:true}).select().single();if(!error)await audit("CREATE",table,data.id,person.name);setMsg(error?.message||"Added.");if(!error){setPerson({...person,name:"",phone:""});load()}}
 async function saveTx(e){e.preventDefault();if(!allowed("admin","manager","member","agent"))return setMsg("Permission denied.");if(!form.person_id||!+form.amount)return setMsg("Select person and amount.");let error,data;
  if(editing){({error}=await supabase.from("transactions").update({...form,amount:+form.amount}).eq("id",editing));if(!error)await audit("UPDATE","transactions",editing,JSON.stringify(form));setMsg(error?.message||"Transaction updated.");setEditing(null)}
  else {({data,error}=await supabase.from("transactions").insert({...form,amount:+form.amount,created_by:session.user.id}).select().single());if(!error)await audit("CREATE","transactions",data.id,JSON.stringify(form));setMsg(error?.message||"Transaction saved.")}
  if(!error){setForm({...form,person_id:"",amount:"",note:""});load()}
 }
 function editTx(t){setEditing(t.id);setForm({type:t.type,person_type:t.person_type,person_id:t.person_id,channel:t.channel,amount:t.amount,note:t.note||"",transaction_date:t.transaction_date});setTab("transactions")}
 async function deleteTx(id){if(!allowed("admin","manager"))return setMsg("Only Admin/Manager can delete.");if(!confirm("Delete this transaction?"))return;const {error}=await supabase.from("transactions").delete().eq("id",id);if(!error)await audit("DELETE","transactions",id,"Transaction deleted");setMsg(error?.message||"Transaction deleted.");if(!error)load()}
 async function addOpening(e){e.preventDefault();if(!allowed("admin","manager"))return setMsg("Permission denied.");const {data,error}=await supabase.from("opening_balances").insert({...opening,amount:+opening.amount,created_by:session.user.id}).select().single();if(!error)await audit("CREATE","opening_balances",data.id,JSON.stringify(opening));setMsg(error?.message||"Opening balance saved.");if(!error){setOpening({...opening,amount:"",note:""});load()}}
 async function dailyClose(){if(!allowed("admin","manager","super_admin"))return setMsg("Only authorized users can close a day.");const net=dayStats.collection-dayStats.fund-dayStats.expense;const {data,error}=await supabase.from("daily_closings").upsert({closing_date:closeDate,total_fund:dayStats.fund,total_collection:dayStats.collection,total_expense:dayStats.expense,net_result:net,closed_by:session.user.id},{onConflict:"closing_date"}).select().single();if(!error)await audit("CLOSE","daily_closings",data.id,closeDate);setMsg(error?.message||"Daily closing saved.");if(!error)load()}
 function personLedger(id,date=""){const rows=tx.filter(t=>t.person_id===id&&(!date||t.transaction_date===date));return sumTx(rows)}
 function reportText(){return `ISF Daily Report ${closeDate}\nFund Given: ৳${money(dayStats.fund)}\nCollection: ৳${money(dayStats.collection)}\nExpense: ৳${money(dayStats.expense)}\nNet Result: ৳${money(dayStats.collection-dayStats.fund-dayStats.expense)}\n\nChannel Closing:\n${channelClosing.map(x=>`${x.channel}: ৳${money(x.closing)}`).join("\n")}`}
 function shareText(){const text=reportText();navigator.clipboard?.writeText(text);if(navigator.share)navigator.share({title:"ISF Daily Report",text}).catch(()=>{});else setMsg("Report copied.")}
 function shareWhatsApp(){window.open(`https://wa.me/?text=${encodeURIComponent(reportText())}`,"_blank")}
 function shareTelegram(){window.open(`https://t.me/share/url?url=&text=${encodeURIComponent(reportText())}`,"_blank")}
 function makePDF(){const d=new jsPDF();d.text("ISF Business Ledger V3",14,15);d.text(`Daily Report: ${closeDate}`,14,23);d.autoTable({startY:30,head:[["Date","Type","Person","Channel","Amount"]],body:dayTx.map(t=>[t.transaction_date,t.type,name(t.person_id),t.channel,money(t.amount)])});const y=(d.lastAutoTable?.finalY||50)+12;d.text(`Fund: ${money(dayStats.fund)} | Collection: ${money(dayStats.collection)} | Expense: ${money(dayStats.expense)}`,14,y);d.text(`Net Result: ${money(dayStats.collection-dayStats.fund-dayStats.expense)}`,14,y+8);return d}
 function exportPDF(){makePDF().save(`ISF-Daily-${closeDate}.pdf`)}
 async function sharePDF(){const d=makePDF();const blob=d.output("blob");const file=new File([blob],`ISF-Daily-${closeDate}.pdf`,{type:"application/pdf"});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:"ISF Daily Report",text:reportText(),files:[file]});return}catch(e){}}exportPDF();setMsg("PDF downloaded. WhatsApp/Telegram direct links cannot attach local files; use the phone Share option when supported.")}
 function exportExcel(){const rows=tx.map(t=>({Date:t.transaction_date,Type:t.type,Person:name(t.person_id),Channel:t.channel,Amount:+t.amount,Note:t.note||""}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Transactions");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(people.map(p=>({Type:p.person_type,Name:p.name,Phone:p.phone||"",Fund:personLedger(p.id).fund,Collection:personLedger(p.id).collection,Expense:personLedger(p.id).expense,Net:personLedger(p.id).collection-personLedger(p.id).fund-personLedger(p.id).expense}))),"People Ledger");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(channelClosing),"Channel Closing");XLSX.writeFile(wb,`ISF-V3-${today()}.xlsx`)}
 const filtered=useMemo(()=>tx.filter(t=>(!filter.date||t.transaction_date===filter.date)&&(!filter.person||t.person_id===filter.person)&&(!filter.channel||t.channel===filter.channel)&&(!filter.type||t.type===filter.type)),[tx,filter]);
 if(!supabase)return <Setup/>;if(loading)return <div className="center">Loading...</div>;if(!session)return <Login login={login} message={msg}/>;
 const tabs=["dashboard","transactions","ledger","closing","people","reports","permissions"];
 return <div className="app"><header className="topbar"><b>ISF Business Ledger <span>V3</span></b><div>{session.user.email}<button onClick={logout}>Logout</button></div></header><div className="layout"><aside>{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</aside><main>{msg&&<div className="notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
 {tab==="dashboard"&&<Dashboard totals={totals} dayStats={dayStats} date={closeDate} people={people} tx={tx}/>} 
 {tab==="transactions"&&<Transactions form={form} setForm={setForm} submit={saveTx} members={members} agents={agents} editing={editing} cancel={()=>{setEditing(null);setForm({...form,person_id:"",amount:"",note:""})}}/>}
 {tab==="ledger"&&<Ledger agents={agents} members={members} ledger={personLedger} date={closeDate} setDate={setCloseDate}/>} 
 {tab==="closing"&&<Closing date={closeDate} setDate={setCloseDate} stats={dayStats} close={dailyClose} openings={opening} setOpening={setOpening} addOpening={addOpening} channelClosing={channelClosing} share={shareText} whatsapp={shareWhatsApp} telegram={shareTelegram} pdf={sharePDF}/>} 
 {tab==="people"&&<People person={person} setPerson={setPerson} add={addPerson} members={members} agents={agents}/>} 
 {tab==="reports"&&<Reports tx={filtered} allTx={tx} name={name} pdf={exportPDF} excel={exportExcel} filter={filter} setFilter={setFilter} edit={editTx} del={deleteTx} people={people}/>} 
 {tab==="permissions"&&<Permissions profile={profile}/>} 
 </main></div></div>
}
const Stat=({title,value})=><div className="card stat"><span>{title}</span><strong>৳ {money(value)}</strong></div>;
function Login({login,message}){return <div className="login"><div className="card login-card"><h1>ISF Business Ledger V3</h1><p>Distributor • Agent • Daily Settlement</p><button className="primary wide" onClick={login}>Continue with Google</button>{message&&<p className="error">{message}</p>}<small>Cloud saved • Mobile friendly • Secure roles</small></div></div>}
function Setup(){return <div className="center"><div className="card"><h2>Supabase setup required</h2><p>Copy .env.example to .env, add Supabase credentials, and run supabase/schema.sql.</p></div></div>}
function Dashboard({totals,dayStats,date,people,tx}){return <section><h1>Dashboard</h1><p className="muted">Business overview — {date}</p><div className="stats"><Stat title="Total Fund Given" value={totals.fund}/><Stat title="Total Collection" value={totals.collection}/><Stat title="Total Expense" value={totals.expense}/><Stat title="Day Net" value={dayStats.collection-dayStats.fund-dayStats.expense}/></div><div className="grid2"><div className="card"><h3>Today's Settlement</h3>{people.slice(0,8).map(p=>{const l=tx.filter(t=>t.person_id===p.id&&t.transaction_date===date);const s=l.reduce((a,t)=>a+(t.type==="fund_given"?+t.amount:t.type==="collection"?-+t.amount:0),0);return <div className="ledgerrow" key={p.id}><b>{p.name}</b><span>{p.person_type}</span><strong>Balance ৳{money(s)}</strong></div>})}</div><div className="card"><h3>Formula</h3><p><b>Net Result = Collection − Fund Given − Expense</b></p><p className="muted">Channel closing = Opening + Collection − Fund Given − Expense.</p></div></div></section>}
function Transactions({form,setForm,submit,members,agents,editing,cancel}){let ps=form.person_type==="member"?members:agents;return <section><h1>{editing?"Edit Transaction":"Transactions"}</h1><form className="card form" onSubmit={submit}><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="collection">Collection</option><option value="fund_given">Fund Given</option><option value="expense">Expense</option></select></label><label>Person Type<select value={form.person_type} onChange={e=>setForm({...form,person_type:e.target.value,person_id:""})}><option value="agent">Agent</option><option value="member">Member</option></select></label><label>Person<select value={form.person_id} onChange={e=>setForm({...form,person_id:e.target.value})}><option value="">Select...</option>{ps.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Channel<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><label>Amount<input required type="number" min="0.01" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><label className="full">Note<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="actions"><button className="primary">{editing?"Update Transaction":"Save Transaction"}</button>{editing&&<button type="button" onClick={cancel}>Cancel</button>}</div></form></section>}
function Ledger({agents,members,ledger,date,setDate}){return <section><div className="section-head"><div><h1>Individual Ledger</h1><p className="muted">Select a date for daily settlement.</p></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="grid2"><LedgerList title="Agents" items={agents} ledger={ledger} date={date}/><LedgerList title="Members / Distributors" items={members} ledger={ledger} date={date}/></div></section>}
function LedgerList({title,items,ledger,date}){return <div className="card"><h3>{title}</h3>{items.map(p=>{const l=ledger(p.id,date);return <div className="ledgerrow" key={p.id}><b>{p.name}</b><span>Fund ৳{money(l.fund)} · Collection ৳{money(l.collection)} · Expense ৳{money(l.expense)}</span><strong>Net ৳{money(l.collection-l.fund-l.expense)}</strong></div>})}</div>}
function Closing({date,setDate,stats,close,openings,setOpening,addOpening,channelClosing,share,whatsapp,telegram,pdf}){return <section><div className="section-head"><div><h1>Daily Closing</h1><p className="muted">Opening → transactions → closing</p></div><input type="date" value={date} onChange={e=>{setDate(e.target.value);setOpening({...openings,date:e.target.value})}}/></div><div className="stats"><Stat title="Fund Given" value={stats.fund}/><Stat title="Collection" value={stats.collection}/><Stat title="Expense" value={stats.expense}/><Stat title="Net Result" value={stats.collection-stats.fund-stats.expense}/></div><div className="card"><h3>Opening Balance</h3><form className="form" onSubmit={addOpening}><label>Channel<select value={openings.channel} onChange={e=>setOpening({...openings,channel:e.target.value})}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><label>Amount<input required type="number" min="0" step=".01" value={openings.amount} onChange={e=>setOpening({...openings,amount:e.target.value,date})}/></label><label>Note<input value={openings.note} onChange={e=>setOpening({...openings,note:e.target.value,date})}/></label><button className="primary">Save Opening</button></form></div><div className="card"><h3>Channel Closing</h3><div className="table-wrap"><table><thead><tr><th>Channel</th><th>Opening</th><th>Movement</th><th>Closing</th></tr></thead><tbody>{channelClosing.map(x=><tr key={x.channel}><td>{x.channel}</td><td>৳{money(x.opening)}</td><td>৳{money(x.movement)}</td><td><b>৳{money(x.closing)}</b></td></tr>)}</tbody></table></div></div><div className="actions"><button className="primary" onClick={close}>Close This Day</button><button onClick={pdf}>📄 Share PDF</button><button onClick={share}>📤 Share</button><button className="wa" onClick={whatsapp}>WhatsApp</button><button className="tg" onClick={telegram}>Telegram</button></div></section>}
function People({person,setPerson,add,members,agents}){return <section><h1>People Management</h1><form className="card form" onSubmit={add}><label>Type<select value={person.type} onChange={e=>setPerson({...person,type:e.target.value})}><option value="agent">Agent</option><option value="member">Member/Distributor</option></select></label><label>Name<input required value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/></label><label>Phone<input value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/></label><button className="primary">Add</button></form><div className="grid2"><List title="Members" items={members}/><List title="Agents" items={agents}/></div></section>}
const List=({title,items})=><div className="card"><h3>{title}</h3>{items.map(x=><div className="listrow" key={x.id}><b>{x.name}</b><span>{x.phone||""}</span></div>)}</div>;
function Reports({tx,allTx,name,pdf,excel,filter,setFilter,edit,del,people}){return <section><div className="section-head"><div><h1>Reports</h1><p className="muted">Search, edit, delete and export.</p></div><div className="actions"><button onClick={pdf}>PDF</button><button onClick={excel}>Excel</button></div></div><div className="card form"><label>Date<input type="date" value={filter.date} onChange={e=>setFilter({...filter,date:e.target.value})}/></label><label>Person<select value={filter.person} onChange={e=>setFilter({...filter,person:e.target.value})}><option value="">All</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Channel<select value={filter.channel} onChange={e=>setFilter({...filter,channel:e.target.value})}><option value="">All</option>{channels.map(c=><option key={c}>{c}</option>)}</select></label><label>Type<select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})}><option value="">All</option><option value="collection">Collection</option><option value="fund_given">Fund Given</option><option value="expense">Expense</option></select></label></div><div className="card"><div className="muted">Showing {tx.length} of {allTx.length} transactions</div><Table tx={tx} name={name} edit={edit} del={del}/></div></section>}
function Table({tx,name,edit,del}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Person</th><th>Channel</th><th>Amount</th><th>Note</th><th>Action</th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td>{t.transaction_date}</td><td>{t.type}</td><td>{name(t.person_id)}</td><td>{t.channel}</td><td>৳ {money(t.amount)}</td><td>{t.note||""}</td><td><button onClick={()=>edit(t)}>Edit</button><button className="danger" onClick={()=>del(t.id)}>Delete</button></td></tr>)}</tbody></table></div>}
function Permissions({profile}){return <section><h1>Role & Security</h1><div className="card"><p>Current role: <b>{profile?.role||"user"}</b></p><p>Roles: Super Admin, Admin, Manager, Member, Agent.</p><p>V3 adds audit logging for create/update/delete/closing actions and role-aware database policies.</p><p className="muted">For production, use one business/organization per dataset and keep Supabase service keys server-side only.</p></div></section>}
createRoot(document.getElementById("root")).render(<App/>);
